server:
  port: 8112

db:
  hostname: localhost
  username: root
  password: 12345678
  schema: sample

logging:
  level:
    root: info
  file:
    path: /root/peacetrue/peacetrue-modules-sample/01-logs
    max-history: 2

peacetrue:
  file:
    base-path: /root/peacetrue/peacetrue-modules-sample/02-upload
