server:
  port: 8112
#  servlet:
#    session:
#      timeout: 10
#      cookie:
#        max-age: 10

db:
  hostname: localhost
  username: root
  password: 12345678
  schema: sample

spring:
  application:
    name: sample
  r2dbc:
    url: r2dbcs:mysql://${db.hostname}:3306/${db.schema}?autoreconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: ${db.username}
    password: ${db.password}
    pool:
      enabled: true
  flyway:
    url: jdbc:mysql://${db.hostname}:3306/${db.schema}
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    baseline-on-migrate: true
    validate-on-migrate: false
  main:
    allow-bean-definition-overriding: true
  session:
    timeout: 3600

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
logging:
  level:
    root: debug
  file:
    max-history: 2
peacetrue:
  spring:
    security:
      ignored-urls: ['/users/register','/users/exists','/index.html','/favicon.ico','/manifest.json','/logo192.png','/static/**']
  enum:
    base-package-paths: com.github.peacetrue
  operator:
    pointcut:
      expression: 'execution(* com.github.peacetrue..*Service.*(*,..))'
  file:
    base-path: /Users/xiayx/Documents/Projects/peacetrue-modules-sample/01-upload

  metadata:
    enable-class: true
    classes:
      '[com.github.peacetrue.user.User]':
        desc: 用户
        properties:
          creatorId:
            reference: com.github.peacetrue.user.User
          modifierId:
            reference: com.github.peacetrue.user.User
      '[com.github.peacetrue.metadata.modules.entity.Entity]':
        desc: 实体
        properties:
          creatorId:
            reference: com.github.peacetrue.user.User
          modifierId:
            reference: com.github.peacetrue.user.User
      '[com.github.peacetrue.metadata.modules.property.Property]':
        desc: 属性
        properties:
          entityId:
            reference: com.github.peacetrue.metadata.modules.entity.Entity
          typeId:
            reference: com.github.peacetrue.dictionary.modules.dictionaryvalue.DictionaryValue
          referenceId:
            reference: com.github.peacetrue.metadata.modules.entity.Entity
          creatorId:
            reference: com.github.peacetrue.user.User
          modifierId:
            reference: com.github.peacetrue.user.User
  log:
    pointcut-infos:
      UserServiceImpl_add:
        module-code: User
        record-id: '#returning.id'
        operate-code: add
        description: '新增用户 #{#returning.username}'
        creator-id: '#{#p0.operatorId}'
      UserServiceImpl_modify:
        module-code: User
        record-id: '#p0.id'
        operate-code: modify
        description: '修改用户 #{#p0.username}'
        creator-id: '#{#p0.operatorId}'
      UserServiceImpl_delete:
        module-code: User
        record-id: '#p0.id'
        operate-code: delete
        description: '删除 #{#returning} 条用户记录'
        creator-id: '#{#p0.operatorId}'
